import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';

const endpoint = '/api/business/';
@Injectable({
  providedIn: 'root'
})
export class FoodService {
  constructor(private http: HttpClient) {}

  getRestaurants() {
    return [
      { name: 'American (New)', value: 'newamerican' },
      { name: 'American (Traditional)', value: 'tradamerican' },
      { name: 'Arabian', value: 'arabian' },
      { name: 'Asian Fusion', value: 'asianfusion' },
      { name: 'Austrian', value: 'austrian' },
      { name: 'Barbeque', value: 'bbq' },
      { name: 'Belgian', value: 'belgian' },
      { name: 'Brasseries', value: 'brasseries' },
      { name: 'Brazilian', value: 'brazilian' },
      { name: 'Breakfast & Brunch', value: 'breakfast_brunch' },
      { name: 'British', value: 'british' },
      { name: 'Buffets', value: 'buffets' },
      { name: 'Bulgarian', value: 'bulgarian' },
      { name: 'Burgers', value: 'burgers' },
      { name: 'Cafes', value: 'cafes' },
      { name: 'Cajun/Creole', value: 'cajun' },
      { name: 'Caribbean', value: 'caribbean' },
      { name: 'Puerto Rican', value: 'puertorican' },
      { name: 'Cheesesteaks', value: 'cheesesteaks' },
      { name: 'Chicken Shop', value: 'chickenshop' },
      { name: 'Chicken Wings', value: 'chicken_wings' },
      { name: 'Chinese', value: 'chinese' },
      { name: 'Comfort Food', value: 'comfortfood' },
      { name: 'Cuban', value: 'cuban' },
      { name: 'Czech', value: 'czech' },
      { name: 'Delis', value: 'delis' },
      { name: 'Diners', value: 'diners' },
      { name: 'Ethiopian', value: 'ethiopian' },
      { name: 'Fast Food', value: 'hotdogs' },
      { name: 'Filipino', value: 'filipino' },
      { name: 'Fish & Chips', value: 'fishnchips' },
      { name: 'Fondue', value: 'fondue' },
      { name: 'Food Court', value: 'food_court' },
      { name: 'Food Stands', value: 'foodstands' },
      { name: 'French', value: 'french' },
      { name: 'German', value: 'german' },
      { name: 'Gluten-Free', value: 'gluten_free' },
      { name: 'Greek', value: 'greek' },
      { name: 'Halal', value: 'halal' },
      { name: 'Hawaiian', value: 'hawaiian' },
      { name: 'Himalayan/Nepalese', value: 'himalayan' },
      { name: 'Honduran', value: 'honduran' },
      { name: 'Hong Kong Style Cafe', value: 'hkcafe' },
      { name: 'Hot Dogs', value: 'hotdog' },
      { name: 'Hot Pot', value: 'hotpot' },
      { name: 'Indian', value: 'indpak' },
      { name: 'Indonesian', value: 'indonesian' },
      { name: 'Irish', value: 'irish' },
      { name: 'Italian', value: 'italian' },
      { name: 'Sicilian', value: 'sicilian' },
      { name: 'Tuscan', value: 'tuscan' },
      { name: 'Japanese', value: 'japanese' },
      { name: 'Ramen', value: 'ramen' },
      { name: 'Kebab', value: 'kebab' },
      { name: 'Korean', value: 'korean' },
      { name: 'Kosher', value: 'kosher' },
      { name: 'Latin American', value: 'latin' },
      { name: 'Live/Raw Food', value: 'raw_food' },
      { name: 'Malaysian', value: 'malaysian' },
      { name: 'Mediterranean', value: 'mediterranean' },
      { name: 'Falafel', value: 'falafel' },
      { name: 'Mexican', value: 'mexican' },
      { name: 'Tacos', value: 'tacos' },
      { name: 'Middle Eastern', value: 'mideastern' },
      { name: 'Egyptian', value: 'egyptian' },
      { name: 'Lebanese', value: 'lebanese' },
      { name: 'Modern European', value: 'modern_european' },
      { name: 'Noodles', value: 'noodles' },
      { name: 'Pizza', value: 'pizza' },
      { name: 'Polish', value: 'polish' },
      { name: 'Polynesian', value: 'polynesian' },
      { name: 'Pop-Up Restaurants', value: 'popuprestaurants' },
      { name: 'Portuguese', value: 'portuguese' },
      { name: 'Russian', value: 'russian' },
      { name: 'Salad', value: 'salad' },
      { name: 'Sandwiches', value: 'sandwiches' },
      { name: 'Scottish', value: 'scottish' },
      { name: 'Seafood', value: 'seafood' },
      { name: 'Soul Food', value: 'soulfood' },
      { name: 'Soup', value: 'soup' },
      { name: 'Southern', value: 'southern' },
      { name: 'Spanish', value: 'spanish' },
      { name: 'Steakhouses', value: 'steak' },
      { name: 'Sushi Bars', value: 'sushi' },
      { name: 'Syrian', value: 'syrian' },
      { name: 'Taiwanese', value: 'taiwanese' },
      { name: 'Tapas Bars', value: 'tapas' },
      { name: 'Tapas/Small Plates', value: 'tapasmallplates' },
      { name: 'Tex-Mex', value: 'tex-mex' },
      { name: 'Thai', value: 'thai' },
      { name: 'Vegan', value: 'vegan' },
      { name: 'Vegetarian', value: 'vegetarian' },
      { name: 'Vietnamese', value: 'vietnamese' },
      { name: 'Waffles', value: 'waffles' },
      { name: 'Wraps', value: 'wraps' }
    ];
  }
}
